### PR TITLE
create a write_log method and use it

### PR DESCRIPTION
**Pull request by videlec**
In order to analyze the patchbot it would be better to have several log files. Besides the 'history.log' we add 'patchbot.log', 'rating.log' and 'rating_summary.txt'.

### CODE REVIEW

**Comment by fchapoton** [comment]
Mon dieu ! This one is a big one.. Can you explain why you need 4 logs ?
Some details points : 
* putting more space before or after = is not pep8 compliant
* xrange is very typical of python2.7, or am I wrong  ? I would like to have py3 compatible code in mind.

I would love to have a log containing the ticket numbers (and the commits) tested since the last change of develop. This would help maybe not to test a ticket too often.

**Comment by videlec** [comment]
Can be less, but I thought those one might be useful:
- history.txt: short log of ticket being tested (the very same as before)
- patchbot.log: log of basically everything (a long version of the one above)
- rating_summary.txt: the same output as "sage -patchbot --list"
- rating.log: everything related to the rating (a detailed version of the one above). It corresponds roughly to what you would have obtained by using the verbose=True option before.

We can add to 'history.txt' a special line when develop does change. Will be easy to do afterwards.

**Comment by videlec** [comment]
Concerning range vs xrange, it does not matter to me. I just found weird that we have to allocate an array of size 1000000 just to count.

**Comment by videlec** [comment]
To see the last diff you would better use "git diff -b" or "git diff -w". I basically changed only the indentation.

**Comment by fchapoton** [comment]
I am testing that. I have seen in the logs that there is already a directory for every tested ticket.
a few remarks after reading the commit:

* in write_log

raise ValueError("logfile = {} must be either None, or a string or a list or a file")

has no .format(something) for the {}

* in main

patchbot.get_ticket(verbose=1)

should use return_all=True maybe ?

**Comment by videlec** [comment]
For the format you are right!

For the get_ticket, it makes no difference. Whatever you ask for, it will parse every ticket... so it will not change anything.

**Comment by fchapoton** [comment]
Humm, but this is in main, where the option --list is supposed to return the list of testable tickets ?

**Comment by videlec** [comment]
It is supposed to "print" the list of testable ticket. And it is what it does. And in a much nicer way than before ; -) Actually, the option "return_all" is never used. So it is even possible to remove it.

**Pull request merged**
