### PR TITLE
handling HTTP errors while asking for json data

### PR DESCRIPTION
**Pull request by videlec**

### CODE REVIEW

**Comment by fchapoton** [comment]
Line:

    print("Getting ticket list...")

is duplicated

**Comment by videlec** [comment]
Right. And I noticed that one of the message in the RuntimeError is wrong. I will propose another commit.

**Comment by fchapoton** [comment]
The ValueError should be a RuntimeError, no ?

**Comment by videlec** [comment]
Yes. sorry.

**Comment by videlec** [comment]
Actually the way I did is not so clean. We might want to pass to the idle state when we fail to connect to the server... to be corrected.

**Pull request merged**
